// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQese7m89wBvaDY1pZVpMt2IAOF-rApjo',
    appId: '1:854758876544:web:c1868dc4ce0ca780878d65',
    messagingSenderId: '854758876544',
    projectId: 'ofm-app-nl',
    authDomain: 'ofm-app-nl.firebaseapp.com',
    storageBucket: 'ofm-app-nl.firebasestorage.app',
    measurementId: 'G-9Z9PGF216G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHk_ly1sX5sonhz9KrVIc1W__mpe0U9a4',
    appId: '1:854758876544:android:c195af43c0389c8b878d65',
    messagingSenderId: '854758876544',
    projectId: 'ofm-app-nl',
    storageBucket: 'ofm-app-nl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rLQ95h3FwHt_BUKIS4CiO7kvvyiCpEc',
    appId: '1:854758876544:ios:276d0d855b350a3f878d65',
    messagingSenderId: '854758876544',
    projectId: 'ofm-app-nl',
    storageBucket: 'ofm-app-nl.firebasestorage.app',
    iosBundleId: 'br.com.htech.ofmAppDemo.ofmDemo',
  );
}
